name: code-quality

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: Initialise pre-commit
        run: uv run pre-commit install-hooks

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: Run tests
        run: uv run pytest .
